spring:
  application:
    name: employee-tracker

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-root.yml

  jpa:
    hibernate:
      ddl-auto: validate